### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by elegaanz** [Plume-org/rocket_csrf#2]
Here is the backtrace I'm getting.

```
thread '<unnamed>' panicked at 'index 5793 out of range for slice of length 5148', libcore/slice/mod.rs:1971:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::slice::slice_index_len_fail
             at libcore/slice/mod.rs:1971
   9: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /checkout/src/libcore/slice/mod.rs:2148
  10: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /checkout/src/libcore/slice/mod.rs:1964
  11: <rocket_csrf::csrf_proxy::CsrfProxy<'a> as std::io::Read>::read
             at /home/baptiste/.cargo/git/checkouts/rocket_csrf-3ea3def0d845c639/6fc55d2/src/csrf_proxy.rs:117
  12: std::io::read_to_end
             at /checkout/src/libstd/io/mod.rs:379
  13: std::io::Read::read_to_end
             at /checkout/src/libstd/io/mod.rs:605
  14: <rocket_csrf::csrf_fairing::CsrfFairing as rocket::fairing::Fairing>::on_response
             at /home/baptiste/.cargo/git/checkouts/rocket_csrf-3ea3def0d845c639/6fc55d2/src/csrf_fairing.rs:415
  15: rocket::rocket::Rocket::dispatch
             at /home/baptiste/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/55459db/core/lib/src/fairing/fairings.rs:70
             at /home/baptiste/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/55459db/core/lib/src/rocket.rs:222
  16: <rocket::rocket::Rocket as hyper::server::Handler>::handle
             at /home/baptiste/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/55459db/core/lib/src/rocket.rs:82
  17: <hyper::server::Worker<H>>::keep_alive_loop
             at /home/baptiste/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:337
  18: <hyper::server::Worker<H>>::handle_connection
             at /home/baptiste/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:283
  19: hyper::server::handle::{{closure}}
             at /home/baptiste/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:242
  20: hyper::server::listener::spawn_with::{{closure}}
             at /home/baptiste/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/listener.rs:50
```

If you need any other info, tell me.

**Comment by trinity-1686a** [comment]
Could you test again? I think I've fixed it.

**Comment by elegaanz** [comment]
I'm getting another error now:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1103`,
 right: `1748`: destination and source slices have different lengths', libcore/slice/mod.rs:1654:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::slice::<impl [T]>::copy_from_slice
             at /checkout/src/libcore/macros.rs:26
   9: <rocket_csrf::csrf_proxy::CsrfProxy<'a> as std::io::Read>::read
             at /home/baptiste/.cargo/git/checkouts/rocket_csrf-3ea3def0d845c639/c852e55/src/csrf_proxy.rs:117
  10: std::io::read_to_end
             at /checkout/src/libstd/io/mod.rs:379
  11: std::io::Read::read_to_end
             at /checkout/src/libstd/io/mod.rs:605
  12: <rocket_csrf::csrf_fairing::CsrfFairing as rocket::fairing::Fairing>::on_response
             at /home/baptiste/.cargo/git/checkouts/rocket_csrf-3ea3def0d845c639/c852e55/src/csrf_fairing.rs:415
  13: rocket::rocket::Rocket::dispatch
             at /home/baptiste/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/55459db/core/lib/src/fairing/fairings.rs:70
             at /home/baptiste/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/55459db/core/lib/src/rocket.rs:222
  14: <rocket::rocket::Rocket as hyper::server::Handler>::handle
             at /home/baptiste/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/55459db/core/lib/src/rocket.rs:82
  15: <hyper::server::Worker<H>>::keep_alive_loop
             at /home/baptiste/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:337
  16: <hyper::server::Worker<H>>::handle_connection
             at /home/baptiste/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:283
  17: hyper::server::handle::{{closure}}
             at /home/baptiste/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:242
  18: hyper::server::listener::spawn_with::{{closure}}
             at /home/baptiste/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/listener.rs:50
```

**Comment by trinity-1686a** [comment]
Fixed that too, now it should be good
